{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-slider
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/slider_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/slider/slider_{{ version }}.tar.gz
  sha256: bc6a17ba5f0b27c8504a1d04992108470f24fd5662fbea14c300ac75fb02fca1

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cli                        # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-vctrs                      # [build_platform != target_platform]
    - r-warp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=3.4.1
    - r-rlang >=1.0.6
    - r-vctrs >=0.5.0
    - r-warp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli >=3.4.1
    - r-rlang >=1.0.6
    - r-vctrs >=0.5.0
    - r-warp

test:
  commands:
    - $R -e "library('slider')"           # [not win]
    - "\"%R%\" -e \"library('slider')\""  # [win]

about:
  home: https://github.com/DavisVaughan/slider
  license: MIT
  summary: Provides type-stable rolling window functions over any R data type. Cumulative and expanding windows are also supported. For more advanced usage, an index can be used as a secondary vector that defines how sliding windows are to be created.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/r
    - oblute
    - rluria14
